version: '3.7'

services:

  db:
    image: postgres
    restart: always
    container_name: postgresql-container
    hostname: myhost
    environment:
      POSTGRES_DB: punto_acceso_wifi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - "9008:5432"